# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c46124b9ebaece434ebcbb68a61cf2d2d6aedc95d6bc63896aab0bd84f3874e8abb2fee8b2bd537ea2600145129ea9e297c24bdde87c18df61f458d3b07ff90

test:
  secret_key_base: 0d4f5a61808ad836b120517ce155b6879686775b3422d8fc7e41feb459025ea3ed16108446185daeb449dc19d26349501a1b745f9f69e3ef97f6ed3c54c67a52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
